version: '3.9'

services:
  redis:
    container_name: redis-blog
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data


  

  backend:
    build: 
      context: ./backend
    container_name: backend-blog
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis
      - db

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev-blog
    restart: always
    ports:
      - '5000:80'   # Web UI
      - '25:25'     # SMTP
      - '143:143'   # IMAP
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
  worker:
    build: 
      context: ./backend
    command: celery -A RestApiBlog worker --loglevel=info
    depends_on:
      - redis
      - backend
      - db
    volumes:
      - .:/app
  sentry:
    image: sentry:latest
    container_name: sentry-web
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - db
    environment:
      SENTRY_SECRET_KEY: "change-this-secret-key"
      SENTRY_POSTGRES_HOST: db
      SENTRY_DB_NAME: blog_db
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis
    command: 
      bash -c "
      sentry upgrade --noinput &&
      sentry run web
      "

  sentry-worker:
    image: sentry:latest
    container_name: sentry-worker
    depends_on:
      - sentry
      - redis
      - db
    environment:
      SENTRY_SECRET_KEY: "change-this-secret-key"
      SENTRY_POSTGRES_HOST: db
      SENTRY_DB_NAME: blog_db
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis
    command: sentry run worker
  
  elasticsearch:
    image: mirror2.chabokan.net/elastic/kibana:8.19.16
    container_name: elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "9200:9200"
      - "9300:9300"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    restart: unless-stopped


  kibana:
    image: mirror2.chabokan.net/elastic/kibana:8.19.16
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    restart: unless-stopped
  logstash:
    image: mirror2.chabokan.net/logstash:9.4.2
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    restart: unless-stopped  
  frontend:
    build:
      context: ./frontend
    container_name: frontend-blog
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  


  

volumes:
  smtp4dev-data:
  postgres_data:
  elasticsearch_data:
