version: "3.9"

services:

  # ======================
  # POSTGRES
  # ======================
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ======================
  # REDIS
  # ======================
  redis:
    image: redis
    container_name: redis-blog
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  # ======================
  # BACKEND
  # ======================
  backend:
    build:
      context: ./backend
    container_name: backend-blog
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./backend:/app
    ports:
      - "9000:9000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      

  # ======================
  # CELERY WORKER
  # ======================
  worker:
    build:
      context: ./backend
    container_name: celery-worker
    command: celery -A RestApiBlog worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
      - db

  # ======================
  # SMTP4DEV
  # ======================
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev-blog
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"

  # ======================
  # ELASTICSEARCH (MIRROR YOU USE)
  # ======================
  elasticsearch:
    image: mirror2.chabokan.net/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  # ======================
  # KIBANA (same mirror family)
  # ======================
  kibana:
    image: mirror2.chabokan.net/elastic/kibana:8.17.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    restart: unless-stopped

  # ======================
  # LOGSTASH (mirror aligned)
  # ======================
  logstash:
    image: mirror2.chabokan.net/logstash:9.4.2
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    restart: unless-stopped

  # ======================
  # FRONTEND
  # ======================
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
# ======================
# VOLUMES
# ======================
volumes:
  postgres_data:
  elasticsearch_data: