# Generated by Django 5.2.1 on 2025-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
