name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker containers
      run: docker compose build

    - name: Start Docker containers
      run: docker compose up -d

    - name: Wait for backend to be ready
      run: |
        for i in {1..30}; do
          if docker ps | grep backend; then
            echo "Backend container is running."
            break
          fi
          echo "Waiting for backend..."
          sleep 2
        done

    - name: Run Django Tests
      run: docker exec backend sh -c "pytest ."
